### ISSUE TITLE
La lógica de selección de operadores está incompleta

### ISSUE THREAD

**Issue by ucusita** [RailsMcguines/GitAct2#1]
Falta la condición final para el caso que no se haya elegido un operador de los cuatro planteados.
Tal vez se podría solucionar con una instrucción ELIF.
Yo podría ayudar con eso.

**Comment by RailsMcguines** [comment]
Excelente compañero ¡adelante!

**Comment by ucusita** [comment]
Aclaro que solo cambiaré la lógica de los operadores, quedan algunos errores por revisar.
